require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/maps", type: :request do
  # Map. As you add validations to Map, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Map.create! valid_attributes
      get maps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      map = Map.create! valid_attributes
      get map_url(map)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_map_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      map = Map.create! valid_attributes
      get edit_map_url(map)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Map" do
        expect do
          post maps_url, params: { map: valid_attributes }
        end.to change(Map, :count).by(1)
      end

      it "redirects to the created map" do
        post maps_url, params: { map: valid_attributes }
        expect(response).to redirect_to(map_url(Map.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Map" do
        expect do
          post maps_url, params: { map: invalid_attributes }
        end.to change(Map, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post maps_url, params: { map: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested map" do
        map = Map.create! valid_attributes
        patch map_url(map), params: { map: new_attributes }
        map.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the map" do
        map = Map.create! valid_attributes
        patch map_url(map), params: { map: new_attributes }
        map.reload
        expect(response).to redirect_to(map_url(map))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        map = Map.create! valid_attributes
        patch map_url(map), params: { map: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested map" do
      map = Map.create! valid_attributes
      expect do
        delete map_url(map)
      end.to change(Map, :count).by(-1)
    end

    it "redirects to the maps list" do
      map = Map.create! valid_attributes
      delete map_url(map)
      expect(response).to redirect_to(maps_url)
    end
  end
end
