Map.create!(
  [
    {#1
      title:         "原池公園スケートパーク",
      content:       "良質な全面コンクリートのパーク。Rがエグい！笑",
      user_id:       "1",
      latitude:      "34.5193499",
      longitude:     "135.4899894",
      picture:  open("./db/fixtures/maps/baraike.png"),
      # trueで[ヘルメット着用][スケートパーク]が選択
      helmet:        "true",
      spot_style:    "true",
    },
    {#2
      title:          "アクシス(axis)",
      content:        "メインのトランジションエリア。どでかいRセクション！初心者には難しいかも、笑",
      user_id:        "2",
      latitude:       "35.970052",
      longitude:      "140.0292885",
      picture:  open( "./db/fixtures/maps/axis.png"),
      helmet:        "false",
      spot_style:    "true",
    },
    {#3
      title:          "永楽スケートパーク",
      content:        "永楽ダム公園の隣にありました。フラットが広く長い。セクション間が遠いから、すぐ疲れる笑",
      user_id:        "3",
      latitude:       "34.3743231",
      longitude:      "135.3697723",
      picture:  open( "./db/fixtures/maps/eiraku.png"),
      helmet:        "false",
      spot_style:    "true",
    },
    {#4
      title:          "姫路市立スケートパーク",
      content:        "思ったより小さい！でもレッジ、ボックス、謎の半球体があり結構楽しめる",
      user_id:        "4",
      latitude:       "34.820876",
      longitude:      "134.673679",
      picture:  open( "./db/fixtures/maps/himeji.png"),
      helmet:         "true",
      spot_style:     "true",
    },
    {#5
      title:          "火打形スケートパーク",
      content:        "巨大バンク、巨大クォーターが存在感ある！特に後者は何もできないくらいデカイ！",
      user_id:        "5",
      latitude:       "34.960403",
      longitude:      "135.751046",
      picture:  open( "./db/fixtures/maps/hiutigata.png"),
      helmet:        "true",
      spot_style:    "true",
    },
    {#6
      title:          "駒沢公園スケートパーク",
      content:        "ミニランプが充実しているので順番を待たなくても利用しやすい",
      user_id:        "6",
      latitude:       "35.625789",
      longitude:      "139.660475",
      picture:  open( "./db/fixtures/maps/komazawa.png"),
      helmet:        "false",
      spot_style:    "true",
    },
    {#7
      title:          "みなとのもり公園スケートパーク",
      content:        "ストリート広場から、ヘルメット必須のRエリアまでとにかく広い！",
      user_id:        "7",
      latitude:       "34.6867201",
      longitude:      "135.2006435",
      picture:  open( "./db/fixtures/maps/minatono.png"),
      helmet:        "false",
      spot_style:    "true",
    },
    {#8
      title:          "ムラサキパーク東京",
      content:        "ムラサキパーク東京店スケート＆BMX専門店併設している！",
      user_id:        "8",
      latitude:       "35.74229",
      longitude:      "139.80921",
      picture:  open( "./db/fixtures/maps/murasaki.png"),
      helmet:        "true",
      spot_style:    "true",
    },
    {#9
      title:          "世田谷公園SLパーク",
      content:        "歴史ある昔ながらのスケートパーク",
      user_id:        "9",
      latitude:       "35.644385",
      longitude:      "139.678945",
      picture:  open( "./db/fixtures/maps/setagaya.png"),
      helmet:        "true",
      spot_style:    "true",
    },
    {#10
      title:          "新横浜公園スケボー広場",
      content:        "広く全面をバンクが囲みルーティーン滑走が可能なパーク",
      user_id:        "10",
      latitude:       "35.512531",
      longitude:      "139.603272",
      picture:  open( "./db/fixtures/maps/shinyoko.png"),
      helmet:        "false",
      spot_style:    "true",
    },
    {#11
      title:          "庄内緑地公園スケートパーク",
      content:        "ちょうど半分にフラットエリアとセクション設置エリアに分かれているので、初心者でも安心！",
      user_id:        "11",
      latitude:       "35.214539",
      longitude:      "136.88694",
      picture:  open( "./db/fixtures/maps/shonai.png"),
      helmet:        "true",
      spot_style:    "true",
    },
    {#12
      title:          "Spotaka PARK FACTORY X",
      content:        "店B1Fにあり通称スポパー。つるつるの路面！少しコンパクトかなー。",
      user_id:        "12",
      latitude:       "34.672955",
      longitude:      "135.497637",
      picture:  open( "./db/fixtures/maps/spotaka.png"),
      helmet:        "false",
      spot_style:    "true",
    },
    {#13
      title:          "たちかわ中央公園スケートパーク",
      content:        "うまい人達が多い。コンパクトな作りのパークかな！",
      user_id:        "13",
      latitude:       "35.703042",
      longitude:      "139.410456",
      picture:  open( "./db/fixtures/maps/tatikawa.png"),
      helmet:        "true",
      spot_style:    "true",
    },
    {#14
      title:          "若宮公園スケートパーク",
      content:        "名古屋といえば！この若宮！路面よくて、変わったボックスと急なランプ！上級者でも楽しめる。",
      user_id:        "14",
      latitude:       "35.159708",
      longitude:      "136.908015",
      picture:  open( "./db/fixtures/maps/wakamiya.png"),
      helmet:        "false",
      spot_style:    "true",
    },
    {#15
      title:          "わかやまスケートパーク",
      content:        "とにかく夏はあつすぎる！！大理石ボックスはかなり流れる！の外れに休憩ベンチや芝生がある。トイレも近い！",
      user_id:        "15",
      latitude:       "34.195458",
      longitude:      "135.142167",
      picture:  open( "./db/fixtures/maps/wakayama.png"),
      helmet:        "true",
      spot_style:    "true",
    },
    ])